trigger: none

schedules:
  - cron: "0 * * * *"  # Runs every 1 hours
    displayName: Integrity Check Every 1 Hours
    branches:
      include:
        - main
    always: true

variables:
  azureServiceConnection: '<your-service-connection>' # MODIFY THIS

parameters:
  - name: policies
    displayName: 'Policies'
    type: object
    default:
      - name: 'prodpolicy' # MODIFY THIS
        resourceGroupName: '<prod-policy-resource-group>' # MODIFY THIS
        customRuleName: '<your-rule-name>' # MODIFY THIS
      - name: 'devtestpolicy' # MODIFY THIS
        resourceGroupName: '<dev-policy-resource-group>' # MODIFY THIS
        customRuleName: '<your-rule-name>' # MODIFY THIS>

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: VerifyConfigIntegrity
    displayName: "Integrity Check for Allowed IP List"
    steps:
      - checkout: self

      - ${{ each policy in parameters.policies }}:
        - task: AzureCLI@2
          displayName: '${{ policy.name }} - Changes'
          inputs:
            azureSubscription: $(azureServiceConnection)
            scriptType: 'bash'
            scriptLocation: 'scriptPath'
            scriptPath: 'scripts/p2_integrity_check.sh'
            arguments: '--policyName ${{ policy.name }} --resourceGroupName ${{ policy.resourceGroupName }} --customRuleName ${{ policy.customRuleName }}'